name: doxy.yml

on:
  push:
    branches:
      - documentation
      - gh-pages

jobs:
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: make Install_doxygen
      - run: make Install_graphviz
      - run: make Creating_documentation
      - name: Push git subdir branch

        uses: s0/git-publish-subdir-action@v2.4.0

        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: DOCS/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}