name: Level up

on:
  push

jobs:
  checking:
    runs-on: ubuntu-latest
    container: kkira07/test:latest
    steps:
      - uses: actions/checkout@v2
      - name: Warnings 
        run: make Warnings
      - name: Report generation
        run: make Report_generation
      - uses: actions/upload-artifact@v2
        with:
          path: ./report.txt
      - name: Build
        run: make run_cpps
      - name: Check memory leak
        run: make Check_mem_leak
      - name: Run tests
        run: make Run_tests
      - name: Check differences
        run: make Check_differences
