name: Level up

on:
  push

jobs:
  checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Valgrind and Cppcheck
        run: sudo apt-get install -y valgrind cppcheck
      - name: Update gcc
        run: sudo apt --only-upgrade install gcc-10 g++-10
      - name: Warnings 
        run: cppcheck *.cpp --enable=warning --error-exitcode=1
      - name: Report generation
        run: cppcheck *.cpp --enable=performance --enable=style --output-file=report.txt
      - uses: actions/upload-artifact@v2
        with:
          path: ./report.txt
      - name: Build
        run: g++-10 -std=c++17 *.cpp
      - name: Check memory leak
        run: valgrind --error-exitcode=1 --leak-check=full ./a.out scneario1.json
      - name: Run tests
        run: ./testing.sh
      - name: Check differences
        run: diff output.txt exp_output.txt
