name: refract test

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container: kkira07/test:latest
    steps:
      - uses: actions/checkout@v2
      - run: g++-10 -std=c++17 *.cpp
      - run: cat steps.txt | ./a.out prepared.json >> out1.txt
      - run: diff output1.txt out1.txt
      - run: cat steps2.txt | ./a.out prepared2.json >> out2.txt
      - run: diff output2.txt out2.txt
