name: Testing

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make -C unit_test/
      - run: unit_test/runTests > unit_test/unittest_results
