name: Unit Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: kkira07/test:latest
    steps:
      - name: Gtest CMake
        run: cd /usr/src/gtest && cmake CMakeLists.txt && make
      - name: Symbolic links
        run: ln -st /usr/lib/ /usr/src/gtest/libgtest.a && ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - uses: actions/checkout@v2
      - name: Build
        run: make Build
      - name: Run tests
        run: make Run_tests2